#+TITLE: Japanese For Me

My tailor-made suite for studying Japanese.

* Setup
** Clone Repository
Download submodules as well:

#+BEGIN_SRC sh
git clone --recurse-submodules https://github.com/makuto/japanese-for-me
#+END_SRC
** Install Dependencies
Jam is used to build Japanese for Me. You will need a C++ toolchain (clang or gcc) installed as well.

#+BEGIN_SRC sh
sudo apt install jam
#+END_SRC

*** For system notifications
Install LibNotify development headers:
#+BEGIN_SRC sh
sudo apt install libnotify-dev
#+END_SRC
** Download and prepare data
*** Dictionary
[[http://edrdg.org/jmdict/edict.html][Download EDICT2]] and extract to ~data/edict2~.
Run the following command to convert EDICT2 to UTF-8:
#+BEGIN_SRC sh
iconv -f EUC-JP -t UTF-8 data/edict2 > data/utf8Edict2
#+END_SRC
TODO: Make this automatic via [[https://www.gnu.org/software/libiconv/][libiconv]].

*** [[https://tatoeba.org/eng/downloads][Tatoeba downloads]] (not required)
Download Japanese sentences, then English sentences, then links
*Download all as Detailed* so that CC attribution can be upheld

[[https://tatoeba.org/eng/terms_of_use#section-6][License]]
** Prepare Anki 
/(for Anki pacer only; not necessary for text analysis)/

Anki is used to manage spaced repitition.

- [[https://foosoft.net/projects/anki-connect/index.html#installation][Install AnkiConnect]]
- Run Anki
** Building
Build CURL and Mecab:
#+BEGIN_SRC sh
./BuildDependencies_Debug.sh
#+END_SRC

Build Japanese for Me:
#+BEGIN_SRC sh
./Build_Debug.sh
#+END_SRC

If you want system-wide notifications, run this instead:
#+BEGIN_SRC sh
./Build_WithLibNotify_Debug.sh
#+END_SRC
* License
The repository itself is under the MIT license.

Tatoeba corpus licensing details are available [[https://tatoeba.org/eng/terms_of_use#section-6][here]]. They vary per-sentence in license, so I will assume attribution is required per-sentence (which is the most restrictive license they have).
